New notebook tutorial
hrwakeford/ExoTiC-ISM pull request #126
Opened 2021-07-21 15:59 UTC by hrwakeford

Tutorial on how to use the transit function and limb-darkening functions independent of the marginalisation framework.

This tutorial walks through the dependencies of the following functions and how to use them from the ExoTiC-ISM package
- `limb_dark_fit`
- `phase_calc`
- `impact_param`
- `occultnl`

2021-07-22 11:03 UTC, lili-alderson commented on notebooks/tutorials/2_ld_and_transit_model-tutorial.ipynb
> +    "Note that some require astropy unit designators to work properly with this code"
I think it would be good to explicitly specify which params need unit designators, rather than leaving this up to the uninitiated to figure out

2021-07-22 11:07 UTC, lili-alderson commented on notebooks/tutorials/2_ld_and_transit_model-tutorial.ipynb
> +    "If you dont want to compute the limb-darkening for whatever reason or you are doing an eclipse set c1-4 manually.\n",
This sentence is confusing to me and doesn't make much sense in the wider context of the notebook

2021-07-22 11:20 UTC, lili-alderson commented on notebooks/tutorials/2_ld_and_transit_model-tutorial.ipynb
> +    "See `margmodule.py` in **ExoTiC-ISM** for details on the `ld_model` and `grat` options"
e.g. here I think something like "For a full list of which models and gratings are supported, see the `ld_model` and `grat` options in `margmodule.py`"
Because from reading that line before seeing `grat` defined in the cell below I had no idea what `grat` was supposed to be referring to and whether that was an advanced user option or something I would need to look into.

2021-07-22 11:27 UTC, lili-alderson commented on notebooks/tutorials/2_ld_and_transit_model-tutorial.ipynb
> +    "Independent of the CONFIG file used in **ExoTiC-ISM**, you can manually input any paramters. These are the ones we will need for the limb-darkening, phase calculation, and transit model. \n",
Perhaps something like "When using the transit and limb darkening functions separately from **ExoTiC-ISM**, you can assign any necessary parameters without changing or creating a new CONFIG file." 
And then potentially specify which parameters are needed for which function/step so that someone coming in who only wants to use one part can do that

2021-07-22 11:31 UTC, lili-alderson commented on notebooks/tutorials/2_ld_and_transit_model-tutorial.ipynb
> +    "Remember when using any part of the **ExoTiC-ISM** package please follow our `citation.txt` file"
The whole notebook would benefit from a better narrative so that someone who is new to transits can jump right in. 

I like batman's tutorial (https://lweb.cfa.harvard.edu/~lkreidberg/batman/tutorial.html#calculating-light-curves) because it walks the reader through in logical steps of "First we need to perform task X so we can achieve goal A. Now we've obtained information Y we can now use function B to get out lightcurves", so the barrier for entry is as low as possible

2021-07-22 11:38 UTC, lili-alderson commented on notebooks/tutorials/2_ld_and_transit_model-tutorial.ipynb
> +    "Remember when using any part of the **ExoTiC-ISM** package please follow our `citation.txt` file"
A standard practice with light curve tutorials seems to be to introduce the concept of the light curve before going into too much detail about the limb darkening functions/options, because that's the order you would teach things to a new student.

If possible, I think this notebook could benefit from something like that, even if it's just a simple introduction of here are some functions, this is what each one does, you can use these to get a final result of xyz. At the moment the title is really the extent of any kind of intro to the notebook, and you need to read the whole thing all the way through to get the final picture of what can be achieved before the reasoning behind each code cell makes sense

2021-07-22 11:41 UTC, lili-alderson requested changes
The README.md is fine and is ready to go.

The notebook code is fine and runs as expected, however the comments need improvements, particularly so that the notebook has enough of a narrative to lower the barrier of entry to match that of a new user

2022-02-02 17:22 UTC, hrwakeford commented
I will be closing this pull request and removing this branch. 
I will add back in this branch and the tutorials in a different way moving forward including additional instruction and transparency.

2022-02-02 17:22 UTC, closed without merging